# .github/workflows/claude-review.yml
name: Claude Code Reviewer

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read          # Claude reads code
  pull-requests: write    # add PR reviews/comments
  issues: write           # open/label/close issues

jobs:
  review:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: anthropics/claude-code-action@v0      # or @v0.0.27 for a fixed tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # from the Claude GitHub App
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
