name: Claude Code Reviewer

# Limits what the job itself can do, even if the token had more.
permissions:
  contents: read         # read the code
  pull-requests: write   # add PR reviews & comments
  issues: write          # open/label/close issues

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  review:
    # only run when someone actually mentions Claude
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Official app → use the standard GITHUB_TOKEN it gives us
      - uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
